version: '3'
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - '8080:8080'
    links:
      - mongo-comment
  mongo-comment:
    container_name: mongo-comment
    restart: always
    image: mongo:latest  
    ports:
      - '27018:27017'
    command: mongod 
      