version: '3'
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    volumes:
      - . /Kloudone/
    ports:
      - '8080:8080'
    links:
      - mongo-comment
  mongo-comment:
    container_name: mongo-comment
    image: mongo
    ports:
      - '27017:27017'